# ----------------------------------------------------------------
# English language
# ----------------------------------------------------------------
[en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1

# banner
[en.params.banner]
enable = true
heading = "What Would You <br> Like To Read Today?"

[en.params.about_me]
# About widget
title = "Hi, I am Alex!"
image = "images/author.jpg"
bio = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vel in in donec iaculis tempus odio nunc laoreet . Libero ullamcorper."


# ----------------------------------------------------------------
# French language
# ----------------------------------------------------------------
[fr]
languageName = "Fr"
languageCode = "fr-fr"
contentDir = "content/french"
weight = 2

# banner
[fr.params.banner]
enable = true
heading = "Qu'aimeriez-vous <br> lire aujourd'hui"

# About widget
[fr.params.about_me]
title = "Salut, je suis Alex!"
image = "images/author.jpg"
bio = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vel in in donec iaculis tempus odio nunc laoreet . Libero ullamcorper."
