baseURL = "https://CodePruner.com/"
languageCode = "en-us"
title = "CodePruner.com"
theme = "ananke"
sectionPagesMenu = "main"

disqusShortname = "codepruner"

[params] 
  googleTagManager = "GTM-P3VB947"
  recent_posts_number = 10
