version: "3.9"
services:
  postgres:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: root 
      POSTGRES_DB: example_datrabase
  adminer:
    image: dockette/adminer
    ports:
      - 8080:80  
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5050:80
    environment:
       PGADMIN_DEFAULT_EMAIL: "pgadmin@codepruner.com"
       PGADMIN_DEFAULT_PASSWORD: "pgadminP@ssw0rd!"