name: CI-dev
on:
  push:
    branches-ignore:
      - "master"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_ENV: production
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.113.0"
          extended: true

      - name: Install npm dependencies
        run: npm install
        working-directory: src/codepruner.com

      - name: Update baseURL in config.toml
        uses: ciiiii/toml-editor@1.0.0
        with:
          file: "src/codepruner.com/config/_default/hugo.toml"
          key: "baseURL"
          value: "https://dev.CodePruner.com/"

      - name: Update GTM in config.toml
        uses: ciiiii/toml-editor@1.0.0
        with:
          file: "src/codepruner.com/config/_default/hugo.toml"
          key: "params.googleTagManager"
          value: "G-1768EEZDT0"

      - name: Build
        run: hugo --source "src/codepruner.com/" --minify --verbose

      - name: Upload ftp
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: "src/codepruner.com/public"
          remoteDir: "/public_html/dev"
          forceSsl: true
