name: CI-dev
on:
  push:
    branches-ignore:
      - "master"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_ENV: production
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.113.0"
          extended: true

      - name: Install npm dependencies
        run: npm install
        working-directory: src/codepruner.com

      - name: Update baseURL in config.toml
        uses: ciiiii/toml-editor@1.0.0
        with:
          file: "src/codepruner.com/config/_default/hugo.toml"
          key: "baseURL"
          value: "https://dev.CodePruner.com/"

      - name: Update GTM in config.toml
        uses: ciiiii/toml-editor@1.0.0
        with:
          file: "src/codepruner.com/config/_default/hugo.toml"
          key: "params.googleTagManager"
          value: "G-1768EEZDT0"

      - name: Build
        run: hugo --source "src/codepruner.com/" --minify --verbose -e production

      - uses: actions/upload-artifact@v3
        with:
          name: dev.codepruner.com
          path: src/codepruner.com/public

      - name: Upload ftp
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: "src/codepruner.com/public/"
          server-dir: "/public_html"
          protocol: ftps
